# -*- coding: utf-8 -*-
"""shemagh_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVsXV7ZVfJTqzPrjgWJ3rULJGY3-Oj6t

import library section
"""

#!unzip -q /content/dal-shemagh-detection-challenge.zip -d /content/

import os
import cv2
import json
import yaml
import glob
import random
import shutil
import base64
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from io import BytesIO
from pathlib import Path
from tqdm import tqdm

# Learning tools and neural networks
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torchvision import ops as tv_ops

# processing libraries
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.metrics import f1_score, accuracy_score

# Install ultralytics if not already installed
#!pip install ultralytics

#YOLO
#!pip install ultralytics
from ultralytics import YOLO
import timm
#!pip install ensemble_boxes
from ensemble_boxes import weighted_boxes_fusion

# image processing
from PIL import Image

class SystemConfig:
      # IMPORTANT: Update this path
    #BASE_DATA_DIR   = Path('/content/images')
    BASE_DATA_DIR = Path('.')
    TRAIN_IMG_DIR   = Path( r'C:\Users\meme7\Downloads\dal-shemagh-detection-challenge\images\train')
    TEST_IMG_DIR    = Path( r'C:\Users\meme7\Downloads\dal-shemagh-detection-challenge\images\test')
    TRAIN_CSV       = Path( r'C:\Users\meme7\Downloads\dal-shemagh-detection-challenge\train_labels.csv')


    # output
    YOLO_OUTPUT_DIR    = Path('shemagh_yolo_models')
    CONVNEXT_OUTPUT_DIR = Path('shemagh_convnext_models')
    PSEUDO_CSV_PATH    = Path('pseudo_correct_labels.csv')
    SUBMISSION_PATH    = Path('final_submission.csv')

    #YOLO ─
    YOLO_BASE_MODEL    = 'yolo11n.pt' #yolo11m.pt is better
    YOLO_IMG_SIZE      = 640
    YOLO_EPOCHS        = 50  #200 is better
    YOLO_BATCH         = 1
    YOLO_DEVICE        = 'cpu'             # GPU (0 or 1) is better
    YOLO_WORKERS       = 0  # 4 is better
    YOLO_ACTIVE_FOLD   = 2

    YOLO_HSV_H = 0.015
    YOLO_HSV_S = 0.8
    YOLO_HSV_V = 0.6

    YOLO_SCALE       = 0.8
    YOLO_MOSAIC      = 1.0
    YOLO_MIXUP       = 0.1
    YOLO_COPY_PASTE  = 0.3
    YOLO_CLOSE_MOSAIC = 50
    YOLO_ERASING     = 0.3

    YOLO_OPTIMIZER   = 'SGD'
    YOLO_LR          = 0.001

    CLASS_NAMES = ['Face', 'Shemagh']
    NUM_DETECT_CLASSES = 2

    # (Pseudo Labeling)
    PSEUDO_SURE_CORRECT_THRESH   = 0.85

    PSEUDO_SURE_INCORRECT_THRESH = 0.15

    # RIGHT POSITION
    HEURISTIC_WEIGHT_SYMMETRY    = 0.8
    HEURISTIC_WEIGHT_DX          = 0.2
    HEURISTIC_FINAL_THRESH       = 0.45

    PSEUDO_TTA_SCALES  = [640, 800, 512]
    PSEUDO_CONF_THRES  = 0.40
    PSEUDO_IOU_WBF     = 0.50

    # ConvNeXt Setting
    CONVNEXT_MODEL_NAME = 'convnext_tiny.fb_in22k_ft_in1k'
    CONVNEXT_NUM_CLASSES = 2     # 0 = TRUE 1 = FALSE
    CONVNEXT_IMG_SIZE    = 224
    CONVNEXT_BATCH       = 16
    CONVNEXT_EPOCHS      = 15
    CONVNEXT_LR          = 5e-5
    CONVNEXT_WEIGHT_DECAY = 1e-2
    CONVNEXT_N_FOLDS     = 5
    CONVNEXT_ACTIVE_FOLD = 0


    IMAGENET_MEAN = [0.485, 0.456, 0.406]
    IMAGENET_STD  = [0.229, 0.224, 0.225]

    FINAL_TTA_SCALES  = [640, 800, 512]  # مقاييس TTA للاستنتاج النهائي
    FINAL_CONF_THRES  = 0.05             # عتبة ثقة منخفضة لزيادة الاستدعاء
    FINAL_IOU_WBF      = 0.60             # عتبة IoU لـ WBF
    FINAL_NMS_THRES   = 0.65             # عتبة IoU لـ NMS بعد WBF

    RANDOM_SEED = 42

    #DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    DEVICE = torch.device('cpu')
""" # Section 3: General Utility Functions
Purpose: These core utility functions ensure deep learning pipeline stability.
          They guarantee exact code reproducibility, standardize object detection
          bounding box formats, and handle robust, safe image loading.
"""

def fix_random_seeds(seed: int = 42) -> None:

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def convert_xyxy_to_xywh(box: list) -> list:

    x1, y1, x2, y2 = box
    width  = x2 - x1
    height = y2 - y1
    cx     = (x1 + x2) / 2.0
    cy     = (y1 + y2) / 2.0
    return [cx, cy, width, height]


def load_image_rgb(image_path: str) -> np.ndarray:

    raw_frame = cv2.imread(str(image_path))
    if raw_frame is None:
        fallback = np.zeros((224, 224, 3), dtype=np.uint8)
        return fallback
    return cv2.cvtColor(raw_frame, cv2.COLOR_BGR2RGB)

def display_detection_result(
    image_rgb: np.ndarray,
    boxes: list,
    scores: list,
    labels: list,
    class_names: list,
    title: str = "results"
) -> None:

    h_img, w_img = image_rgb.shape[:2]
    display_frame = image_rgb.copy()


    palette = {0: (0, 120, 255), 1: (0, 220, 80)}

    for box, score, lbl in zip(boxes, scores, labels):
        cls_idx = int(lbl)
        px1 = int(box[0] * w_img)
        py1 = int(box[1] * h_img)
        px2 = int(box[2] * w_img)
        py2 = int(box[3] * h_img)
        color = palette.get(cls_idx, (200, 200, 200))

        cv2.rectangle(display_frame, (px1, py1), (px2, py2), color, 2)
        label_text = f"{class_names[cls_idx]}: {score:.2f}"
        cv2.putText(
            display_frame, label_text,
            (px1, max(py1 - 8, 12)),
            cv2.FONT_HERSHEY_SIMPLEX, 0.55, color, 2
        )

    plt.figure(figsize=(10, 10))
    plt.imshow(display_frame)
    plt.title(title, fontsize=14)
    plt.axis('off')
    plt.tight_layout()
    plt.show()

"""# Section 4: YOLO11 Training with K-Fold Cross-Validation
responsible for training the YOLO11 model using K-Fold Cross-Validation.

Features:
- Splits data into K random, reproducible folds.
- Automatically generates YAML configuration files for each fold.
- Applies intensive color augmentation to combat domain drift.
- Saves validation results individually for each fold.

"""

class YOLOTrainer:


    def __init__(self, cfg: SystemConfig):
        self.cfg = cfg
        self.cfg.YOLO_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    def _build_fold_yaml(
        self,
        fold_idx: int,   #The index of the current data fold
        train_txt_path: str, # text image path for train
        val_txt_path: str # for validate
    ) -> str:

        yaml_filename = f"fold_{fold_idx}_config.yaml"
        yaml_content = {
            'path':  str(self.cfg.BASE_DATA_DIR),
            'train': os.path.abspath(train_txt_path),
            'val':   os.path.abspath(val_txt_path),
            'nc':    self.cfg.NUM_DETECT_CLASSES,
            'names': self.cfg.CLASS_NAMES,
        }
        with open(yaml_filename, 'w') as yaml_file:
            yaml.dump(yaml_content, yaml_file)
        return os.path.abspath(yaml_filename)

    def train_single_fold(self, fold_idx: int, train_images: list, val_images: list) -> dict:

        # YOLO format
        train_txt = f"train_fold{fold_idx}.txt"
        val_txt   = f"val_fold{fold_idx}.txt"
        with open(train_txt, 'w') as f:
            f.write("\n".join(train_images))
        with open(val_txt, 'w') as f:
            f.write("\n".join(val_images))

        fold_yaml = self._build_fold_yaml(fold_idx, train_txt, val_txt)


        torch.cuda.empty_cache()
        detector = YOLO(self.cfg.YOLO_BASE_MODEL)

        detector.train(
            data       = fold_yaml,
            epochs     = self.cfg.YOLO_EPOCHS,
            imgsz      = self.cfg.YOLO_IMG_SIZE,
            batch      = self.cfg.YOLO_BATCH,
            device     = self.cfg.YOLO_DEVICE,
            seed       = self.cfg.RANDOM_SEED,
            workers    = self.cfg.YOLO_WORKERS,
            deterministic = True,


            hsv_h = self.cfg.YOLO_HSV_H,
            hsv_s = self.cfg.YOLO_HSV_S,
            hsv_v = self.cfg.YOLO_HSV_V,
            scale = self.cfg.YOLO_SCALE,

            mosaic       = self.cfg.YOLO_MOSAIC,
            mixup        = self.cfg.YOLO_MIXUP,
            copy_paste   = self.cfg.YOLO_COPY_PASTE,
            close_mosaic = self.cfg.YOLO_CLOSE_MOSAIC,
            erasing      = self.cfg.YOLO_ERASING,

            optimizer = self.cfg.YOLO_OPTIMIZER,
            lr0       = self.cfg.YOLO_LR,

            project = str(self.cfg.YOLO_OUTPUT_DIR),
            name    = f'fold_{fold_idx}',
        )

        # save result
        val_stats = detector.val()
        fold_results = val_stats.results_dict if val_stats else {}
        return fold_results
    # Executes K-Fold training.
    def run_kfold_training(self) -> dict:

        all_images = sorted([
            str(p) for p in self.cfg.TRAIN_IMG_DIR.iterdir()
            if p.suffix.lower() in ['.jpg', '.jpeg', '.png']
        ])

        splitter = KFold(
            n_splits   = self.cfg.CONVNEXT_N_FOLDS,
            shuffle    = True,
            random_state = self.cfg.RANDOM_SEED,
        )

        accumulated_results = {}

        for fold_num, (train_idx, val_idx) in enumerate(splitter.split(all_images)):
            if fold_num != self.cfg.YOLO_ACTIVE_FOLD:
                continue

            print(f"\n{'='*60}")
            print(f" YOLO11 Training - Fold {fold_num + 1}/{self.cfg.CONVNEXT_N_FOLDS}")
            print(f"{'='*60}")

            train_list = [all_images[i] for i in train_idx]
            val_list   = [all_images[i] for i in val_idx]

            fold_metrics = self.train_single_fold(fold_num, train_list, val_list)
            accumulated_results[fold_num] = fold_metrics

            # Save an instant copy of the results
            backup_path = self.cfg.YOLO_OUTPUT_DIR / 'kfold_metrics_backup.json'
            with open(backup_path, 'w') as bkp:
                json.dump(accumulated_results, bkp, indent=2)
            print(f" The result saved in {backup_path}")

        return accumulated_results

    def get_best_model_path(self) -> Path:

        model_path = Path(
            r"C:\Users\meme7\Downloads\runs\detect\shemagh_yolo_models\fold_2\weights\best.pt"
        )
        return model_path

"""# Section 5: Geometric Logic and Pseudo-Label Generation
Executes spatial reasoning and multi-axial geometry calculations to
          validate Shemagh placement on the head. It filters duplicate boxes,
          measures axial symmetry, checks alignment limits, and scores the overall
          wearing quality to automatically generate high-confidence pseudo-labels.
"""

class GeometricPositionAnalyzer:


    def remove_duplicate_detections(
        self,
        shemagh_boxes: list,
        overlap_threshold: float = 0.50
    ) -> list:

        if not shemagh_boxes:
            return []

        refined = []
        # Descending order by area (largest first)
        sorted_boxes = sorted(
            shemagh_boxes,
            key=lambda b: b[2] * b[3],
            reverse=True
        )

        for candidate in sorted_boxes:
            bx, by, bw, bh = candidate
            is_duplicate = False

            for accepted in refined:
                ax, ay, aw, ah = accepted

                ix1 = max(bx - bw / 2, ax - aw / 2)
                iy1 = max(by - bh / 2, ay - ah / 2)
                ix2 = min(bx + bw / 2, ax + aw / 2)
                iy2 = min(by + bh / 2, ay + ah / 2)
                intersection_area = max(0, ix2 - ix1) * max(0, iy2 - iy1)

                overlap_ratio = intersection_area / (bw * bh + 1e-9)
                if overlap_ratio > overlap_threshold:
                    is_duplicate = True
                    break

            if not is_duplicate:
                refined.append(candidate)

        return refined

    def compute_placement_features(
        self,
        head_box: list,
        shemagh_box: list
    ) -> dict:
        """
    Computes geometric features to evaluate the correctness of the Shemagh placement.

    Calculated Features:
    - ioh: Intersection over Head ratio (coverage of the head by the Shemagh).
    - symmetry: Degree of Shemagh symmetry around the central vertical axis of the head.
    - dx_norm: Relative horizontal offset between their centers.
    - starts_at_top: Does the Shemagh start from the top of the head?
    - is_above: Is the Shemagh positioned above the head? (Essential condition).
    - head_flat: Is the head flat (high width-to-height ratio)?

    Args:
        head_box (list): Head bounding box coordinates [cx, cy, w, h].
        shemagh_box (list): Shemagh bounding box coordinates [cx, cy, w, h].

    Returns:
        dict: A dictionary containing the calculated geometric features.


        """
        hx, hy, hw, hh = head_box
        sx, sy, sw, sh = shemagh_box

        #  Intersection over Head (IoH)
        inter_x1 = max(hx - hw / 2, sx - sw / 2)
        inter_y1 = max(hy - hh / 2, sy - sh / 2)
        inter_x2 = min(hx + hw / 2, sx + sw / 2)
        inter_y2 = min(hy + hh / 2, sy + sh / 2)
        intersection = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)
        head_area = hw * hh
        ioh_score = intersection / head_area if head_area > 0 else 0.0

        # Symmetry about the Vertical Axis
        head_area_half = head_area / 2
        # LEFT SYMMETRY
        left_x1 = max(hx - hw / 2, sx - sw / 2)
        left_x2 = min(hx,          sx + sw / 2)  # center of the head
        left_y1 = max(hy - hh / 2, sy - sh / 2)
        left_y2 = min(hy + hh / 2, sy + sh / 2)
        left_overlap = max(0, left_x2 - left_x1) * max(0, left_y2 - left_y1)

        # RIGHT SYMMETRY
        right_x1 = max(hx,          sx - sw / 2)  # center of the head
        right_x2 = min(hx + hw / 2, sx + sw / 2)
        right_y1 = max(hy - hh / 2, sy - sh / 2)
        right_y2 = min(hy + hh / 2, sy + sh / 2)
        right_overlap = max(0, right_x2 - right_x1) * max(0, right_y2 - right_y1)

        if head_area_half > 0:
            symmetry_score = abs(
                (left_overlap  / head_area_half) -
                (right_overlap / head_area_half)
            )
        else:
            symmetry_score = 1.0  # Bad value by default

        # Normalized Horizontal Displacement
        dx_normalized = abs(sx - hx) / hw if hw > 0 else 1.0

        # Spatial Relation Metrics
        head_top_edge    = hy - hh / 2
        shemagh_top_edge = sy - sh / 2

        # Does the Shemagh start above the head's upper quartile?
        starts_at_head_top = shemagh_top_edge < (hy - hh / 4)
        # Is the Shemagh above the head? (Natural constraint for correct placement)
        shemagh_above_head = shemagh_top_edge < head_top_edge
        # Is the head flat? (Potential face detection anomaly)
        head_appears_flat  = hh < (hw * 0.9)

        return {
            'ioh':          ioh_score,
            'symmetry':     symmetry_score,
            'dx_norm':      dx_normalized,
            'starts_at_top': starts_at_head_top,
            'is_above':     shemagh_above_head,
            'head_flat':    head_appears_flat,
        }
    # Calculate the correct positioning of the geometric features.
    def score_placement(self, features: dict, cfg: SystemConfig) -> float:
        # Exclusion Criteria
        # Reject if the Shemagh is not above the head
        if not features['is_above']:
            return float('-inf')
        if features['head_flat'] and features['ioh'] < 0.80:
            return float('-inf')


        placement_score = (
            features['ioh']
            - cfg.HEURISTIC_WEIGHT_SYMMETRY * features['symmetry']
            - cfg.HEURISTIC_WEIGHT_DX       * features['dx_norm']
        )

      # Additional bonus if the Shemagh starts from the top
        if features['starts_at_top']:
            placement_score += 0.05

        return placement_score

class PseudoLabelGenerator:


    def __init__(self, yolo_model_path: str, cfg: SystemConfig):

        self.cfg = cfg
        self.analyzer = GeometricPositionAnalyzer()
        print(f"Download the YOLO template from: {yolo_model_path}")
        self.detector = YOLO(yolo_model_path)

    def _run_tta_detection(self, image_path: str) -> tuple:
        boxes_per_scale  = []
        scores_per_scale = []
        labels_per_scale = []

        for scale in self.cfg.PSEUDO_TTA_SCALES:
            inference_output = self.detector.predict(
                image_path,
                imgsz   = scale,
                conf    = self.cfg.PSEUDO_CONF_THRES,
                augment = True,
                verbose = False,
            )[0]

            if len(inference_output.boxes) > 0:
                boxes_per_scale.append(
                    inference_output.boxes.xyxyn.cpu().tolist()
                )
                scores_per_scale.append(
                    inference_output.boxes.conf.cpu().tolist()
                )
                labels_per_scale.append(
                    inference_output.boxes.cls.cpu().tolist()
                )

        if not boxes_per_scale:
            return [], [], []

        # MERGE
        merged_boxes, merged_scores, merged_labels = weighted_boxes_fusion(
            boxes_per_scale,
            scores_per_scale,
            labels_per_scale,
            weights = None,
            iou_thr = self.cfg.PSEUDO_IOU_WBF,
            skip_box_thr = self.cfg.PSEUDO_CONF_THRES,
        )
        return merged_boxes, merged_scores, merged_labels

    def analyze_single_image(self, image_path: str) -> dict:

        filename = os.path.basename(image_path)
        boxes, scores, labels = self._run_tta_detection(image_path)

        head_detections     = [
            convert_xyxy_to_xywh(b)
            for b, l in zip(boxes, labels) if int(l) == 0
        ]
        raw_shemagh_boxes   = [
            convert_xyxy_to_xywh(b)
            for b, l in zip(boxes, labels) if int(l) == 1
        ]
        clean_shemagh_boxes = self.analyzer.remove_duplicate_detections(raw_shemagh_boxes)

        is_correct    = 0
        best_score    = -1.0

        if head_detections and clean_shemagh_boxes:
            for h_box in head_detections:
                for s_box in clean_shemagh_boxes:
                    geo_features   = self.analyzer.compute_placement_features(h_box, s_box)
                    pair_score     = self.analyzer.score_placement(geo_features, self.cfg)
                    if pair_score > best_score:
                        best_score = pair_score

            if best_score > self.cfg.HEURISTIC_FINAL_THRESH:
                is_correct = 1

        # Prediction
        pred_parts = [
            f"{int(l)} {s:.4f} "
            f"{convert_xyxy_to_xywh(b)[0]:.4f} "
            f"{convert_xyxy_to_xywh(b)[1]:.4f} "
            f"{convert_xyxy_to_xywh(b)[2]:.4f} "
            f"{convert_xyxy_to_xywh(b)[3]:.4f}"
            for b, s, l in zip(boxes, scores, labels)
        ]
        prediction_str = " ".join(pred_parts) if pred_parts else "-"

        return {
            'filename':          filename,
            'right_place':       is_correct,
            'max_score':         best_score,
            'prediction_string': prediction_str,
        }

    def generate_pseudo_labels(self, output_csv: Path) -> pd.DataFrame:

        test_image_paths = sorted([
            str(p) for p in self.cfg.TEST_IMG_DIR.iterdir()
            if p.suffix.lower() in ['.jpg', '.jpeg', '.png']
        ])

        print(f"\nProcessing {len(test_image_paths)} images to generate pseudo-labels...")
        all_analysis = []

        for img_path in tqdm(test_image_paths, desc="Engineering Analysis"):
            result = self.analyze_single_image(img_path)
            all_analysis.append(result)

        df_all = pd.DataFrame(all_analysis)

        # JUST CORRECT PSEUDO
        pseudo_records = []
        for _, row in df_all.iterrows():
            if row['max_score'] >= self.cfg.PSEUDO_SURE_CORRECT_THRESH:
                pseudo_records.append({'filename': row['filename'], 'label': 1})
            elif row['max_score'] <= self.cfg.PSEUDO_SURE_INCORRECT_THRESH:
                pseudo_records.append({'filename': row['filename'], 'label': 0})

        df_pseudo = pd.DataFrame(pseudo_records)
        # SAVE JUST THE CORRECT
        df_correct_pseudo = df_pseudo[df_pseudo['label'] == 1].copy()
        df_correct_pseudo.to_csv(output_csv, index=False)

        print(f"Saved {len(df_correct_pseudo)} pseudo-labels to: {output_csv}")
        return df_correct_pseudo

"""# Section 6: ConvNeXt Dataset and Image Transformations
Builds a robust PyTorch Dataset that safely streams images into memory
          and converts arrays to PIL format. It applies targeted data augmentations
          like random rotation, horizontal flipping, and color jitter to train ConvNeXt.
"""

class ShemaghClassificationDataset(Dataset):

    def __init__(self, dataframe: pd.DataFrame, transform=None):

        self.df        = dataframe.reset_index(drop=True)
        self.transform = transform

    def __len__(self) -> int:
        return len(self.df)
    # get a single sample by knowing its index.
    def __getitem__(self, sample_idx: int):

        record = self.df.iloc[sample_idx]
        image_rgb = load_image_rgb(record['path'])

        # Convert NumPy → PIL for Torchvision compatibility
        pil_image = Image.fromarray(image_rgb)

        if self.transform:
            pil_image = self.transform(pil_image)

        label = torch.tensor(int(record['right_place']), dtype=torch.long)
        return pil_image, label


def get_classification_transforms(phase: str, cfg: SystemConfig):

    target_size = cfg.CONVNEXT_IMG_SIZE
    mean        = cfg.IMAGENET_MEAN
    std         = cfg.IMAGENET_STD

    if phase == 'train':
        return transforms.Compose([
            transforms.Resize((target_size, target_size)),
            # Random horizontal reinforcement (symmetrical shemagh)
            transforms.RandomHorizontalFlip(p=0.5),
            # Simple rotation to simulate different shooting angles
            transforms.RandomRotation(degrees=15),
            # Color variation to enhance generalization
            transforms.ColorJitter(
                brightness=0.2, contrast=0.2,
                saturation=0.2, hue=0.02
            ),
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std),
        ])
    else:
        # Check: No reinforcements, just standard normalization
        return transforms.Compose([
            transforms.Resize((target_size, target_size)),
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std),
        ])

"""# Section 7: ConvNeXt Training and Validation Loops
Implements the neural network execution pipeline for ConvNeXt.
         It automates data fusion (combining original and pseudo-labels),
          calculates class weights to handle dataset imbalance, and executes
          a Stratified K-Fold loop tracking validation F1-scores for optimal checkpoints.
"""

def run_training_epoch(
    model: nn.Module,
    data_loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    loss_fn: nn.Module,
    device: torch.device
) -> tuple:

    model.train()
    total_loss    = 0.0
    correct_count = 0
    sample_count  = 0

    for batch_images, batch_labels in tqdm(data_loader, desc="training", leave=False):
        batch_images = batch_images.to(device)
        batch_labels = batch_labels.to(device)

        optimizer.zero_grad()
        logits = model(batch_images)
        batch_loss = loss_fn(logits, batch_labels)
        batch_loss.backward()
        optimizer.step()

        total_loss    += batch_loss.item()
        preds          = torch.argmax(logits, dim=1)
        correct_count += (preds == batch_labels).sum().item()
        sample_count  += batch_labels.size(0)

    avg_loss = total_loss / len(data_loader)
    accuracy = correct_count / sample_count
    return avg_loss, accuracy


def run_validation_epoch(
    model: nn.Module,
    data_loader: DataLoader,
    loss_fn: nn.Module,
    device: torch.device
) -> tuple:

    model.eval()
    total_loss = 0.0
    all_preds  = []
    all_labels = []

    with torch.no_grad():
        for batch_images, batch_labels in tqdm(data_loader, desc="التحقق", leave=False):
            batch_images = batch_images.to(device)
            batch_labels = batch_labels.to(device)

            logits     = model(batch_images)
            batch_loss = loss_fn(logits, batch_labels)
            total_loss += batch_loss.item()

            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch_labels.cpu().numpy())

    avg_loss    = total_loss / len(data_loader)
    val_acc     = accuracy_score(all_labels, all_preds)
    val_f1      = f1_score(all_labels, all_preds, zero_division=0)
    return avg_loss, val_acc, val_f1


class ConvNeXtClassifierTrainer:

    def __init__(self, cfg: SystemConfig):
        self.cfg = cfg
        self.cfg.CONVNEXT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    def _build_combined_dataframe(self) -> pd.DataFrame:

        df_original = pd.read_csv(self.cfg.TRAIN_CSV)
        df_original['path'] = df_original['filename'].apply(
            lambda fn: str(self.cfg.TRAIN_IMG_DIR / fn)
        )

        # Download fake labels (if any)
        combined_frames = [df_original]

        if self.cfg.PSEUDO_CSV_PATH.exists():
            df_pseudo = pd.read_csv(self.cfg.PSEUDO_CSV_PATH)
            #  label → right_place
            if 'label' in df_pseudo.columns:
                df_pseudo = df_pseudo.rename(columns={'label': 'right_place'})
            df_pseudo['path'] = df_pseudo['filename'].apply(
                lambda fn: str(self.cfg.TEST_IMG_DIR / fn)
            )
            combined_frames.append(df_pseudo)
            print(f"Added {len(df_pseudo)} pseudo-labels from: {self.cfg.PSEUDO_CSV_PATH}")

        else:
            print("Pseudo-labels file not found, training on original data only.")

        df_combined = pd.concat(combined_frames, axis=0, ignore_index=True)
        class_distribution = df_combined['right_place'].value_counts().to_dict()
        print(f"Class distribution after merging: {class_distribution}")
        return df_combined

    def _compute_class_weights(self, df: pd.DataFrame) -> torch.Tensor:
        counts     = df['right_place'].value_counts()
        n_negative = counts.get(0, 1)  # number of negative
        n_positive = counts.get(1, 1)  # Number of Positive
        # Positive class weight = ratio of negative samples to positive samples
        positive_weight = n_negative / n_positive
        weights = torch.tensor([1.0, float(positive_weight)]).to(self.cfg.DEVICE)
        print(f"Class weights: [1.0, {positive_weight:.3f}]")
        return weights

    def train_all_folds(self) -> None:
        df_full    = self._build_combined_dataframe()
        cls_weights = self._compute_class_weights(df_full)
        loss_fn    = nn.CrossEntropyLoss(weight=cls_weights)

        fold_splitter = StratifiedKFold(
            n_splits     = self.cfg.CONVNEXT_N_FOLDS,
            shuffle      = True,
            random_state = self.cfg.RANDOM_SEED,
        )

        for fold_num, (train_idx, val_idx) in enumerate(
            fold_splitter.split(df_full, df_full['right_place'])
        ):
            # Train the active fold only
            if fold_num > 0:
                break

            print(f"\n{'='*60}")
            print(f" ConvNeXt Training - Fold {fold_num + 1}/{self.cfg.CONVNEXT_N_FOLDS}")
            print(f"{'='*60}")

            fold_train_df = df_full.iloc[train_idx].reset_index(drop=True)
            fold_val_df   = df_full.iloc[val_idx].reset_index(drop=True)


            train_dataset = ShemaghClassificationDataset(
                fold_train_df,
                transform=get_classification_transforms('train', self.cfg)
            )
            val_dataset = ShemaghClassificationDataset(
                fold_val_df,
                transform=get_classification_transforms('val', self.cfg)
            )

            train_loader = DataLoader(
                train_dataset,
                batch_size  = self.cfg.CONVNEXT_BATCH,
                shuffle     = True,
                num_workers = 0,  # 0 Safe on Windows and most environments
            )
            val_loader = DataLoader(
                val_dataset,
                batch_size  = self.cfg.CONVNEXT_BATCH,
                shuffle     = False,
                num_workers = 0,
            )

            # Form creation: ConvNeXt designer built on ImageNet-22k
            convnext = timm.create_model(
                self.cfg.CONVNEXT_MODEL_NAME,
                pretrained   = True,
                num_classes  = self.cfg.CONVNEXT_NUM_CLASSES,
            ).to(self.cfg.DEVICE)

            optimizer = optim.AdamW(
                convnext.parameters(),
                lr           = self.cfg.CONVNEXT_LR,
                weight_decay = self.cfg.CONVNEXT_WEIGHT_DECAY,
            )

            best_f1    = 0.0
            model_path = self.cfg.CONVNEXT_OUTPUT_DIR / f'convnext_fold{fold_num}_best.pth'

            for epoch_num in range(self.cfg.CONVNEXT_EPOCHS):
                train_loss, train_acc = run_training_epoch(
                    convnext, train_loader, optimizer, loss_fn, self.cfg.DEVICE
                )
                val_loss, val_acc, val_f1 = run_validation_epoch(
                    convnext, val_loader, loss_fn, self.cfg.DEVICE
                )

                print(
                    f"  The era {epoch_num+1:02d}/{self.cfg.CONVNEXT_EPOCHS} | "
                    f"Training loss : {train_loss:.4f} | "
                    f"F1 Verification: {val_f1:.4f}"
                )

                # Save the model if F1 improves
                if val_f1 > best_f1:
                    best_f1 = val_f1
                    torch.save(convnext.state_dict(), model_path)
                    print(f" ✓ Saved the best model (F1={best_f1:.4f}) to: {model_path}")

            print(f"\n Fold {fold_num+1} finished. Best F1: {best_f1:.4f}")
            del convnext, optimizer
            torch.cuda.empty_cache()

    def get_best_model_path(self) -> Path:
        return (
            self.cfg.CONVNEXT_OUTPUT_DIR
            / f'convnext_fold{self.cfg.CONVNEXT_ACTIVE_FOLD}_best.pth'
        )

"""# Section 8: Final Inference Pipeline (TTA + WBF + NMS + ConvNeXt)
Implements the final multi-stage inference sequence for submission.
          It runs multi-scale YOLO predictions with Test-Time Augmentation (TTA),
          fuses bounding boxes using Weighted Boxes Fusion (WBF), applies
          class-wise NMS filtering, conditions the ConvNeXt wearing classifier
          on positive detections, and formats the output into standard submission strings.
"""

class FinalInferencePipeline:

    def __init__(
        self,
        yolo_path: str,
        convnext_path: str,
        cfg: SystemConfig
    ):
        self.cfg = cfg

        # Download YOLO Template
        print(f"Download YOLO from: {yolo_path}")
        self.yolo_detector = YOLO(yolo_path)

        # Download ConvNeXt Template
        print(f"Download ConvNeXt from: {convnext_path}")
        self.classifier = timm.create_model(
            cfg.CONVNEXT_MODEL_NAME,
            pretrained  = False,
            num_classes = cfg.CONVNEXT_NUM_CLASSES,
        )
        saved_weights = torch.load(convnext_path, map_location=cfg.DEVICE)
        self.classifier.load_state_dict(saved_weights)
        self.classifier.to(cfg.DEVICE)
        self.classifier.eval()
        self.inference_transform = get_classification_transforms('val', cfg)

    def _detect_with_tta(self, image_path: str) -> tuple:
        boxes_tta  = []
        scores_tta = []
        labels_tta = []

        for scale in self.cfg.FINAL_TTA_SCALES:
            scale_results = self.yolo_detector.predict(
                image_path,
                imgsz   = scale,
                conf    = self.cfg.FINAL_CONF_THRES,
                augment = True,
                verbose = False,
            )[0]

            if len(scale_results.boxes) > 0:
                boxes_tta.append(scale_results.boxes.xyxyn.cpu().tolist())
                scores_tta.append(scale_results.boxes.conf.cpu().tolist())
                labels_tta.append(scale_results.boxes.cls.cpu().tolist())

        if not boxes_tta:
            return [], [], []

        # Apply WBF: Consolidates redundant boxes by averaging spatial coordinates.
        # Superior to standard NMS as it retains variance through fusion rather than suppression.
        fused_boxes, fused_scores, fused_labels = weighted_boxes_fusion(
            boxes_tta,
            scores_tta,
            labels_tta,
            weights  = None,
            iou_thr  = self.cfg.FINAL_IOU_WBF,
            skip_box_thr = self.cfg.FINAL_CONF_THRES,
        )
        return fused_boxes, fused_scores, fused_labels

    def _apply_classwise_nms(
        self,
        raw_boxes: list,
        raw_scores: list,
        raw_labels: list
    ) -> tuple:
        # Apply class-wise NMS post-WBF to prevent redundant overlapping boxes per object.
        if len(raw_boxes) == 0:
            return [], [], []

        boxes_t  = torch.tensor(raw_boxes,  dtype=torch.float32)
        scores_t = torch.tensor(raw_scores, dtype=torch.float32)
        labels_t = torch.tensor(raw_labels, dtype=torch.int64)

        kept_indices = []
        for cls_id in labels_t.unique():
            class_mask     = (labels_t == cls_id)
            class_boxes    = boxes_t[class_mask]
            class_scores   = scores_t[class_mask]
            original_idx   = torch.where(class_mask)[0]

            # Standard NMS per category
            nms_keep = tv_ops.nms(class_boxes, class_scores, self.cfg.FINAL_NMS_THRES)
            kept_indices.extend(original_idx[nms_keep].tolist())

        kept_indices = sorted(kept_indices)
        return (
            [raw_boxes[i]  for i in kept_indices],
            [raw_scores[i] for i in kept_indices],
            [raw_labels[i] for i in kept_indices],
        )

    def _classify_placement(self, image_path: str) -> int:

        image_rgb    = load_image_rgb(image_path)
        pil_image    = Image.fromarray(image_rgb)
        input_tensor = self.inference_transform(pil_image).unsqueeze(0).to(self.cfg.DEVICE)

        with torch.no_grad():
            logits       = self.classifier(input_tensor)
            probabilities = torch.softmax(logits, dim=1)
            predicted_cls = torch.argmax(probabilities, dim=1).item()

        return predicted_cls

    def process_single_image(self, image_path: str) -> dict:

        filename = os.path.basename(image_path)

        # Stage 1: YOLO TTA
        raw_boxes, raw_scores, raw_labels = self._detect_with_tta(image_path)

        # Stage 2: NMS For each category
        nms_boxes, nms_scores, nms_labels = self._apply_classwise_nms(
            raw_boxes, raw_scores, raw_labels
        )

        # Determine whether there is a face covering or a headscarf
        has_face    = any(int(l) == 0 for l in nms_labels)
        has_shemagh = any(int(l) == 1 for l in nms_labels)

        # Stage 3: ConvNeXt (only if something is revealed)
        is_correct_placement = 0
        if has_face or has_shemagh:
            is_correct_placement = self._classify_placement(image_path)

        # Build prediction series
        parts = [
            f"{int(l)} {s:.4f} "
            f"{convert_xyxy_to_xywh(b)[0]:.4f} "
            f"{convert_xyxy_to_xywh(b)[1]:.4f} "
            f"{convert_xyxy_to_xywh(b)[2]:.4f} "
            f"{convert_xyxy_to_xywh(b)[3]:.4f}"
            for b, s, l in zip(nms_boxes, nms_scores, nms_labels)
        ]
        prediction_str = " ".join(parts) if parts else "-"

        return {
            'filename':          filename,
            'right_place':       is_correct_placement,
            'prediction_string': prediction_str,
        }

    def generate_submission(self) -> pd.DataFrame:
        test_images = sorted([
            str(p) for p in self.cfg.TEST_IMG_DIR.iterdir()
            if p.suffix.lower() in ['.jpg', '.jpeg', '.png']
        ])

        print(f"\nStarting final inference on {len(test_images)} images...")
        submission_rows = []

        for img_path in tqdm(test_images, desc="Final Conclusion"):
            row = self.process_single_image(img_path)
            submission_rows.append(row)

        df_submission = pd.DataFrame(submission_rows)
        df_submission.to_csv(self.cfg.SUBMISSION_PATH, index=False)

        positive_count = df_submission['right_place'].sum()
        print(f"\n✓ Saved submission file to: {self.cfg.SUBMISSION_PATH}")
        print(f" Total positive predictions (correct placement): {positive_count}")
        print(f" Total images: {len(df_submission)}")

        return df_submission

"""# Section 9: Single-Image Inference and Visualization (Interactive Use)
---



"""

def run_single_image_demo(
    image_path: str,  #image_path (str): Path to the image file to be tested.
    yolo_model_path: str, #yolo_model_path (str): Path to the trained YOLO model weights.
    convnext_model_path: str, #convnext_model_path (str): Path to the trained ConvNeXt model weights.
    cfg: SystemConfig = None #cfg (SystemConfig, optional): Configuration object. Defaults to None (auto-generated if not passed).
) -> None:
    if cfg is None:
        cfg = SystemConfig()

    pipeline = FinalInferencePipeline(yolo_model_path, convnext_model_path, cfg)
    result   = pipeline.process_single_image(image_path)

    print("\n" + "="*50)
    print(f"Image: {result['filename']}")
    print(f"Status: {'✓ Correct' if result['right_place'] == 1 else '✗ Incorrect or Unspecified'}")
    print(f"Predictions: {result['prediction_string']}")
    print("="*50)

    # Visual Results
    raw_boxes, raw_scores, raw_labels = pipeline._detect_with_tta(image_path)
    nms_boxes, nms_scores, nms_labels = pipeline._apply_classwise_nms(
        raw_boxes, raw_scores, raw_labels
    )
    image_rgb = load_image_rgb(image_path)
    title = f"Result: {'Correct Placement ✓' if result['right_place'] else 'Incorrect Placement ✗'}"
    display_detection_result(
        image_rgb, nms_boxes, nms_scores, nms_labels,
        cfg.CLASS_NAMES, title=title
    )

"""# Section 10: Main Entry Point

---

Main entry point to execute the complete end-to-end computer vision pipeline.

    Execution Steps:
    1. Fix all random seeds to guarantee result reproducibility.
    2. Train the YOLO11 model using K-Fold Cross-Validation.
    3. Run spatial reasoning to generate high-confidence pseudo-labels.
    4. Train the ConvNeXt classifier with blended datasets and class balancing.
    5. Execute the final test-time inference sequence to generate the submission file.
"""

def main():
    # Step 0: Initial Configuration
    cfg = SystemConfig()
    fix_random_seeds(cfg.RANDOM_SEED)
    print(f"Device being used: {cfg.DEVICE}")

    # Step 1: YOLO11 Training
    print("\n" + "━"*70)
    print(" Phase 1: Training the YOLO11 Model for Face and Shemagh Detection")
    print("━"*70)
    yolo_trainer = YOLOTrainer(cfg)
    yolo_trainer.run_kfold_training()
    yolo_model_path = yolo_trainer.get_best_model_path()
    print(f" Best YOLO model path: {yolo_model_path}")

    # Step 2: Pseudo-Label Generation
    print("\n" + "━"*70)
    print(" Phase 2: Generating Pseudo-Labels via Geometric Logic")
    print("━"*70)
    pseudo_generator = PseudoLabelGenerator(str(yolo_model_path), cfg)
    pseudo_generator.generate_pseudo_labels(cfg.PSEUDO_CSV_PATH)

    # Step 3: ConvNeXt Training
    print("\n" + "━"*70)
    print(" Phase 3: Training the ConvNeXt Model for Shemagh Placement Classification")
    print("━"*70)
    convnext_trainer = ConvNeXtClassifierTrainer(cfg)
    convnext_trainer.train_all_folds()
    convnext_model_path = convnext_trainer.get_best_model_path()
    print(f" Best ConvNeXt model path: {convnext_model_path}")

    # Step 4: Final Inference
    print("\n" + "━"*70)
    print(" Phase 4: Running the Final Inference Pipeline (TTA + WBF + NMS + ConvNeXt)")
    print("━"*70)
    final_pipeline = FinalInferencePipeline(
        str(yolo_model_path),
        str(convnext_model_path),
        cfg,
    )
    df_final = final_pipeline.generate_submission()

    print("\n" + "━"*70)
    print(f" ✓ All phases completed. Submission file saved to: {cfg.SUBMISSION_PATH}")
    print("━"*70)

    return df_final


# Execution Trigger
if __name__ == '__main__':
    final_submission = main()